/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Graphics;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import modelo.Purchases;
import modelo.PurchasesDao;

/**
 *
 * @author Usuario
 */
public class Print extends javax.swing.JFrame {

    Purchases pur = new Purchases();
    PurchasesDao pur_dao = new PurchasesDao();
    DefaultTableModel model = new DefaultTableModel();

    public Print(int id) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Factura de Compra");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        txt_print_inbox.setText("Id de compra: "+id);
        listAllPurchasesDetails(id);
        calcularTotal();
    }

    public void listAllPurchasesDetails(int id) {
        List<Purchases> list = pur_dao.listPurchasesDetailQuery(id);
        model = (DefaultTableModel) tbt_pur_details.getModel();
        Object [] row=new Object[7];
         for (int i = 0; i < list.size(); i++) {
                row[0]=list.get(i).getProduct_name();
                row[1]=list.get(i).getPurchase_amount();
                row[2]=list.get(i).getPurchase_price();
                row[3]=list.get(i).getPurchase_subtotal();
                row[4]=list.get(i).getSupplier_name_product();
                row[5]=list.get(i).getPurcharser();
                row[6]=list.get(i).getCreated();
                model.addRow(row);
            }
         tbt_pur_details.setModel(model);
   }
    
    //calcular total
      public void calcularTotal() {
        double total = 0.0;
        int numRow = tbt_pur_details.getRowCount();
        for (int i = 0; i < numRow; i++) {
            //indice de la columna que se sumara
            total = total + Double.parseDouble(String.valueOf(tbt_pur_details.getValueAt(i, 3)));
        }
        txt_total.setText("" + total);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Form_print = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label_print = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_print_inbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbt_pur_details = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        btn_print_pur = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(620, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Form_print.setBackground(new java.awt.Color(0, 204, 204));
        Form_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_print.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/farmacia.png"))); // NOI18N
        jPanel2.add(label_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -6, 100, 80));

        Form_print.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 70));

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vida Natural");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 160, -1));

        txt_print_inbox.setEditable(false);
        txt_print_inbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_print_inboxActionPerformed(evt);
            }
        });
        jPanel1.add(txt_print_inbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 150, -1));

        Form_print.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 650, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Detalles de la compra:");
        Form_print.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        tbt_pur_details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio", "SubTotal", "Proveedor", "Comprado por:", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbt_pur_details);
        if (tbt_pur_details.getColumnModel().getColumnCount() > 0) {
            tbt_pur_details.getColumnModel().getColumn(0).setMinWidth(100);
            tbt_pur_details.getColumnModel().getColumn(5).setMinWidth(110);
            tbt_pur_details.getColumnModel().getColumn(6).setMinWidth(80);
        }

        Form_print.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 650, 140));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Total:");
        Form_print.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));
        Form_print.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 100, -1));

        getContentPane().add(Form_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 400));

        btn_print_pur.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_print_pur.setText("Imprimir");
        btn_print_pur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_print_purActionPerformed(evt);
            }
        });
        getContentPane().add(btn_print_pur, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_print_inboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_print_inboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_print_inboxActionPerformed

    private void btn_print_purActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_print_purActionPerformed
        Toolkit tk= Form_print.getToolkit(); //herramienta para imprimir en windows
        PrintJob pj= tk.getPrintJob(this,null,null); //el mas usado para imprimir en java
        Graphics gra=pj.getGraphics();
        Form_print.print(gra);
        gra.dispose();
        pj.end();
    }//GEN-LAST:event_btn_print_purActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Form_print;
    private javax.swing.JButton btn_print_pur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_print;
    private javax.swing.JTable tbt_pur_details;
    private javax.swing.JTextField txt_print_inbox;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
